version: '3.7'

services:
  face-detection:
    container_name: face-detection
    build:
      context: ../
      dockerfile: deployment/face-detection/Dockerfile
    env_file:
      - ../.env
    ports:
      - "9000:9000"
    restart: always
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - shinobi

  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:dev
    container_name: shinobi
    environment:
      - PLUGIN_KEYS=$PLUGIN_YMLS
      - SSL_ENABLED='false'
    volumes:
      - $HOME/Shinobi/config:/config
      - $HOME/Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - $HOME/Shinobi/database:/var/lib/mysql
      - $HOME/Shinobi/videos:/home/Shinobi/videos
      - $HOME/Shinobi/plugins:/home/Shinobi/plugins
      - /dev/shm/Shinobi/streams:/dev/shm/streams
    ports:
      - "8080:8080"
    restart: unless-stopped
