"""Add users

Revision ID: ae7cc9df04b8
Revises: b982b3876470
Create Date: 2024-07-26 15:15:14.077670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7cc9df04b8'
down_revision: Union[str, None] = 'b982b3876470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detected_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('monitor_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_users_id'), 'detected_users', ['id'], unique=False)
    op.create_index(op.f('ix_detected_users_monitor_id'), 'detected_users', ['monitor_id'], unique=False)
    op.add_column('incidents', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'last_update')
    op.drop_index(op.f('ix_detected_users_monitor_id'), table_name='detected_users')
    op.drop_index(op.f('ix_detected_users_id'), table_name='detected_users')
    op.drop_table('detected_users')
    # ### end Alembic commands ###
