"""Update DetectedUser model

Revision ID: ba3446209ae4
Revises: ae7cc9df04b8
Create Date: 2024-07-29 22:27:12.913793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3446209ae4'
down_revision: Union[str, None] = 'ae7cc9df04b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_users', sa.Column('last_update', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detected_users', 'last_update')
    # ### end Alembic commands ###
