"""Update DetectedUser model with match score

Revision ID: f88b423ad35c
Revises: 956a9f61e819
Create Date: 2024-07-30 10:06:16.416631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88b423ad35c'
down_revision: Union[str, None] = '956a9f61e819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detected_users', sa.Column('match_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detected_users', 'match_score')
    # ### end Alembic commands ###
